[package]
name = "egglog-experimental"
version = "0.1.0"
edition = "2021"

[dependencies]
egglog = "0.2.0"
smallvec = "1.13.2"

[dev-dependencies]
criterion = "0.5.1"

# [[bin]]
# name = "profile_oracle"
# path = "src/bin/profile_oracle.rs"

[lib]
name = "egglog_experimental"
path = "src/lib.rs"

[patch.crates-io]
egglog = { git = "file:///C:/Users/TomBi/IdeaProjects/egglog", rev = "e0129c15753c4760516d7362362f3c64e03a2d67" }
